### ISSUE TITLE
Port installer to Bash

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/install#217]
The installer should be ported (with identical logic on macOS to begin with) to Bash for:

1. future versions of macOS that don't include Ruby
2. avoid failing with messed up `ruby` in the users' `$PATH`
3. allow using the same installer for Homebrew on Linux (CC @Homebrew/linux).

The best strategy to begin with would be a line-by-line port.

Ideally the same thing would be done for the uninstaller but this isn't essential for a first PR.

**Comment by sjackman** [comment]
Note that the Linuxbrew installer works for both macOS and Linux:
https://github.com/Linuxbrew/install/blob/master/install

**Comment by MikeMcQuaid** [comment]
@sjackman A PR replacing this one with that would probably be a good starting point? Will likely need some review/tweaking.

**Comment by sjackman** [comment]
Okay, I can take that one, adding support for Linux to this repo.

**Comment by joehorsnell** [comment]
> 1. future versions of macOS that don't include Ruby

My first thought when I initially saw was, "that seems unlikely to me, given how long Ruby has been included with macOS", but then I read this! https://tidbits.com/2019/06/25/apple-to-deprecate-scripting-languages-in-future-versions-of-macos/

Was that point above based on reading the 10.15 beta notes @MikeMcQuaid, or just great prescience?!

Also, out of interest, what's your reasoning for wanting to port the installer to bash, rather than keep it in Ruby but dynamically install a vendor Ruby, like Linuxbrew install does? Homebrew itself and all the formulae need Ruby anyway, so that seems like a good approach?

**Comment by MikeMcQuaid** [comment]
> Was that point above based on reading the 10.15 beta notes @MikeMcQuaid, or just great prescience?!

Beta notes 😁 

> Also, out of interest, what's your reasoning for wanting to port the installer to bash, rather than keep it in Ruby but dynamically install a vendor Ruby, like Linuxbrew install does? Homebrew itself and all the formulae need Ruby anyway, so that seems like a good approach?

It avoids duplicating the Homebrew Ruby vendoring process and there's nothing in this installer that needs to be in Ruby.

**Comment by joehorsnell** [comment]
Ah, ok. I didn't realise Homebrew had a Ruby vendoring process, I just assumed it would use the system Ruby, but obviously it woks on Linux too, so that makes sense.

No sense in extracting the [vendoring process](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/vendor-install.sh) out into the installer, so it can be shared? Or is it too ingrained into Homebrew?

**Comment by sjackman** [comment]
Linuxbrew uses a quick and dirty reimplementation of the vendoring process. See https://github.com/Linuxbrew/install/blob/master/install-ruby
I agree with Mike that I'd probably prefer to see the installer rewritten in shell.

**Comment by MikeMcQuaid** [comment]
> No sense in extracting the [vendoring process](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/vendor-install.sh) out into the installer, so it can be shared?

We can't meaningfully share code between both in a way that's not going to cause duplication. I also don't see the advantage, personally, other than Ruby being nicer to write in.

**Comment by mikesep** [comment]
I've been starting to work on a shell version of a combined mac/linux homebrew installer. I'm not quite sticking to a line-by-line port, since some concepts don't translate well, in my opinion.

If anyone else has been looking into this, or if we've changed our mind and don't actually want a shell rewrite, please let me know. 😄

**Comment by sjackman** [comment]
I'm looking forward to seeing the PR, @mikesep! Feel free to open a draft or work-in-progress PR if you'd like some intermediate feedback before blazing through to the end.

**Comment by sjackman** [comment]
The installer on Linux supports both macOS and Linux. https://github.com/linuxbrew/install

**Comment by mikesep** [comment]
> The installer on Linux supports both macOS and Linux. [Linuxbrew/install](https://github.com/Linuxbrew/install)

Yup, I'm using that (and the diff between this repo) as the basis for my work. 👍 The Linuxbrew installer has drifted a very tiny amount from the Homebrew one (just in supported versions, last time I checked).

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/install/pull/79 to merge Homebrew/master into Linuxbrew/master.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/install/pull/256 is almost ready to 🚢 and is a good implementation. If anyone here wants to give it some review: we'd appreciate that. 

After it's merged we can start looking at making this installer support both macOS and Linux.
