### ISSUE TITLE
macOS 10.15.1 install.sh 

### ISSUE THREAD

**Issue by RandyMcMillan** [Homebrew/install#556]
I had to manually install

[Command_Line_Tools_for_Xcode_11.3.1.dmg](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.3.1/Command_Line_Tools_for_Xcode_11.3.1.dmg)

for the 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

command to work...

[#L636](https://github.com/Homebrew/install/blob/master/install.sh#L636)

```
 /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
```

command assumes that  /Library/Developer/CommandLineTools exists - when in fact it may not. If macOS is upgraded then it may be preserved from a prior install - but in this case - macOS 10.15.1 was installed cleanly. 

----
Notes:

• Once Command_Line_Tools_for_Xcode_11.3.1.dmg was installed - the [install.sh](https://github.com/Homebrew/install/blob/master/install.sh) script worked.

[Command_Line_Tools_for_Xcode_11.3.1.dmg](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.3.1/Command_Line_Tools_for_Xcode_11.3.1.dmg)

Reproduce: 

---

• The Command_Line_Tools_for_Xcode_\<version\>.dmg is specific to macOS 10.15.1

• This bug may be on Apple's side - as it doesn't find an appropriate Command_Line_Tools_for_Xcode_\<version\>.dmg for macOS 10.15.1

**Comment by carlocab** [comment]
It's hard to say what happened if you don't include the full output of what you saw from the installer script.

The line you reference assumes that `/Library/Developer/CommandLineTools` because the script will install the CLT for you if you don't already have it. This is why there is a [`should_install_command_line_tools`](https://github.com/Homebrew/install/blob/61f40dfdd5f904122f7cfbc2d4c91b31290d4608/install.sh#L218) check.
