### ISSUE TITLE
Investigate .pkg and sharball installers

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/install#634]
These could be [generated using CPack](https://cmake.org/cmake/help/latest/manual/cpack-generators.7.html) and then generated on Homebrew/brew releases.

**Comment by XuehaiPan** [comment]
How about `.sh` installer with embedded binaries. Since `brew` is a command-line tool and doesn't have a  GUI interface, it's natural for users to run the installer in Terminal rather than a GUI `.pkg` installer.

`conda` provides offline self-contained `.sh` installer. In the installer, it extract embedded binaries with command `dd`.

```bash
CONDA_EXEC="$PREFIX/conda.exe"
# 3-part dd from https://unix.stackexchange.com/a/121798/34459
# this is similar below with the tarball payload - see shar.py in constructor to see how
#    these values are computed.
{
    dd if="$THIS_PATH" bs=1 skip=28139                  count=4629                      2>/dev/null
    dd if="$THIS_PATH" bs=16384        skip=2                      count=978                   2>/dev/null
    dd if="$THIS_PATH" bs=1 skip=16056320                   count=307                     2>/dev/null
} > "$CONDA_EXEC"

chmod +x "$CONDA_EXEC"
```

See also [conda/constructor](https://github.com/conda/constructor).

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Would rather avoid including binaries here and instead let Homebrew bootstrap those itself. Would want to include essentially a tarball of just Homebrew/brew. homebrew-core isn't work handling as we're planning on using `HOMEBREW_INSTALL_FROM_API` to handle that case.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry for the wasted work @XuehaiPan 😭
